Add anonymous login
vape-tool/VapeTool-Webapp pull request #81
Opened 2020-08-11 14:54 UTC by gbaranski

closes #62

2020-08-11 14:54 UTC, gbaranski commented
@stasbar done

2020-08-11 14:56 UTC, stasbar commented
lemme see

2020-08-11 15:22 UTC, gbaranski commented
@stasbar yo eazy how is it going?

2020-08-11 15:27 UTC, stasbar commented
w8 a moment, I just need to come off the piano for a moment

2020-08-12 01:55 UTC, stasbar commented on src/services/user.ts
> +    message: 'Only for logged users!',
You need to be logged in

2020-08-12 01:56 UTC, stasbar commented on src/services/user.ts
> +    description: 'Click on the notification to redirect to login page',
Click to login

2020-08-16 12:43 UTC, gbaranski commented on src/services/user.ts
> +    description: 'Click on the notification to redirect to login page',
Done

2020-08-16 12:43 UTC, gbaranski commented on src/services/user.ts
> +    message: 'Only for logged users!',
Done

2020-08-16 12:43 UTC, gbaranski commented
@stasbar done

2020-08-18 19:54 UTC, stasbar commented
display "You need to be logged in" instead. Basically, everywhere currentUser is used and is undefined (because is anonymous) should display "You need to be logged in"
<img width="898" alt="Screenshot 2020-08-18 at 21 52 18" src="https://user-images.githubusercontent.com/9407590/90558897-18c68580-e19d-11ea-8c3a-c9f3838eac08.png">

2020-08-18 19:56 UTC, stasbar commented
<img width="122" alt="Screenshot 2020-08-18 at 21 52 43" src="https://user-images.githubusercontent.com/9407590/90559141-79ee5900-e19d-11ea-8a77-5f5b3b3743e4.png">
Prevent adding new content

2020-08-27 19:43 UTC, stasbar commented
@gbaranski have you seen my comments ?

2020-08-27 21:21 UTC, gbaranski commented
@stasbar yes i will fix that in a moment

2020-08-27 21:46 UTC, gbaranski commented
<img width="749" alt="Screen Shot 2020-08-27 at 23 40 07" src="https://user-images.githubusercontent.com/34353640/91497672-a7828300-e8be-11ea-8ab1-7686abac4e85.png">

working, users are unable to edit anything when they are logged as anonymous

<img width="876" alt="Screen Shot 2020-08-27 at 23 41 06" src="https://user-images.githubusercontent.com/34353640/91497727-c8e36f00-e8be-11ea-805d-fef684a84692.png">

create button is gone when logged as anonymous

2020-09-01 10:53 UTC, stasbar requested changes
Besides that, it should be good

2020-09-01 10:53 UTC, stasbar commented on src/components/ItemView/ItemView.tsx
> +  };
create `usersOnly` middleware so the common logic can be extracted.

```
const onLikeClick = usersOnly(() => {
    like(what, item.uid, user.uid);
})
const onReportClick = usersOnly(() => {
    report(what, item.uid, user.uid);
})
const submitComment = usersOnly(() => {
    commentItem(what, draftComment, item.uid, user);
})
```

you know I'm taking about ?
pm me if you need assistance sir

2020-09-01 10:53 UTC, stasbar commented on src/components/ItemView/ItemView.tsx
> +  const currentUser = initialState?.firebaseUser as User;
```
  const { initialState } = useModel('@@initialState');
  const { currentUser, firebaseUser } = initialState || {};
```
then you need to replace all instance of `currentUser`'s to `firebaseUser`'s and `user`'s to `currentUser`'s and ``

2020-09-02 18:14 UTC, stasbar approved these changes

2020-09-02 21:01 UTC, merged